# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('subject', models.CharField(max_length=64)),
                ('plainContent', models.TextField()),
                ('htmlContent', models.TextField(null=True)),
                ('campaignName', models.CharField(max_length=32)),
                ('tags', models.CharField(help_text='Insert all tags separated by a comma.', max_length=64)),
                ('attachments', models.FileField(upload_to=b'')),
            ],
        ),
    ]
