# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailTemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='email',
            name='campaignName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='htmlContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='tags',
            field=models.CharField(blank=True, help_text='Insert all tags separated by a comma.', max_length=64, null=True),
        ),
    ]
