# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailTemplates', '0002_auto_20151225_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='htmlContent',
            new_name='htmlBody',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='plainContent',
            new_name='plainBody',
        ),
    ]
