# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailTemplates', '0003_auto_20151225_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fileAttachment', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_mailTemplates.Email'),
        ),
    ]
