# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailTemplates', '0004_auto_20160201_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=128),
        ),
    ]
