# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailTemplates', '0005_auto_20160201_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='fileAttachment',
            field=models.FileField(upload_to=''),
        ),
    ]
