# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 19:51
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailTemplates', '0005_auto_20160201_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='htmlBody',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
